le/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^', include('webapp.urls')),
    url(r'^login/',  RedirectView.as_view(url='/webapp/login')),
    url(r'^logout/',  RedirectView.as_view(url='/webapp/logout')),
    url(r'^register/',  RedirectView.as_view(url='/webapp/register')),
    url(r'^register_expert/',  RedirectView.as_view(url='/webapp/register_expert')),
    url(r'^register_client/',  RedirectView.as_view(url='/webapp/register_client')),
    url(r'^experts_details/',  RedirectView.as_view(url='/webapp/experts_details')),
    url(r'^clients_details/',  RedirectView.as_view(url='/webapp/clients_details')),

    url(r'^webapp/', include('webapp.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

webapp/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
from webapp.views import terms, privacy, about, logout_user, search, messages, news, interviews, create_message, create_rating, register, register_expert, register_client

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^experts_details/$', views.experts_details, name = 'experts_details'),
    url(r'^clients_details/$', views.clients_details, name = 'clients_details'),
    url(r'^login/', login, {'template_name': 'registration/login.html' }),
    url(r'^logout/', logout_user),
    url(r'^register_expert/$', views.register_expert, name = 'register_expert'),
    url(r'^register_client/$', views.register_client, name = 'register_client'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^search/$', views.search, name = 'search'),
    url(r'^expert/$', views.expert, name = 'expert'),
    url(r'^messages/$', views.messages, name = 'messages'),
    url(r'^news/$', views.news, name = 'news'),
    url(r'^interviews/$', views.interviews, name = 'interviews'),
    url(r'^update_profile/$', views.update_profile, name = 'update_profile'),
    url(r'^create_message/$', views.create_message, name = 'create_message'),
    url(r'^create_rating/$', views.create_rating, name = 'create_rating'),
    url(r'^terms/$', views.terms, name = 'terms'),
    url(r'^privacy/$', views.privacy, name = 'privacy'),
    url(r'^about/$', views.about, name = 'about'),
    url(r'^press/$', views.press, name = 'press'),
    url(r'^contact/$', views.contact, name = 'contact'),
    url(r'^remove_profile/$', views.remove_profile, name = 'remove_profile'),
    url(r'^lang/$', views.lang, name = 'lang'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import (
  AbstractBaseUser, BaseUserManager
)

from django_countries.fields import CountryField
from datetime import datetime

class UserManager(BaseUserManager):

  def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
    if not email:
      raise ValueError("Users must have email address")
    if not password:
      raise ValueError("Users must have password")

    user = self.model(
      email = self.normalize_email(email)
    )

    user.set_password(password)

    user.staff   = is_staff
    user.admin   = is_admin
    user.active  = is_active

    user.save(using=self._db)
    return user

  def create_superuser(self, email, password=None):
    user = self.create_user(
      email,
      password=password,
      is_admin=True
    )
    return user

  def create_staff(self, email, password=None):
    user = self.create_user(
      email,
      password=password,
      is_staff=True
    )
    return user



#Custom User
class User(AbstractBaseUser):
  email            = models.EmailField(max_length=255, unique=True)
  active           = models.BooleanField(default=True)
  staff            = models.BooleanField(default=False)
  admin            = models.BooleanField(default=False)
  timestamp        = models.DateTimeField(auto_now_add=True)

  first_name       = models.CharField(max_length=255, blank=True, null=True)
  last_name        = models.CharField(max_length=255 , blank=True, null=True)
  username         = models.CharField(max_length=255 , blank=True, null=True)

  phone            = models.CharField(max_length=255, blank=True, null=True)
  mobile           = models.CharField(max_length=255, blank=True, null=True)
  web              = models.CharField(max_length=255, blank=True, null=True)

  street           = models.CharField(max_length=255, blank=True, null=True)
  street_number    = models.CharField(max_length=255, blank=True, null=True)
  city             = models.CharField(max_length=255, blank=True, null=True)
  country          = CountryField(default ='CZ')
  zipcode          = models.CharField(max_length=255, blank=True, null=True)
  district         = models.CharField(max_length=255, blank=True, null=True)
  district_id      = models.IntegerField(blank=True, null=True)

  latitude         = models.CharField(max_length=255, blank=True, null=True)
  longtitude       = models.CharField(max_length=255, blank=True, null=True)

  company          = models.CharField(max_length=255, blank=True, null=True)
  category_id      = models.IntegerField(blank=True, null=True)
  experience       = models.IntegerField(blank=True, null=True)

  hour_rate_from   = models.IntegerField(blank=True, null=True)
  hour_rate_to     = models.IntegerField(blank=True, null=True)

  bio              = models.TextField(max_length=5000, blank=True, null=True)
  expertise        = models.CharField(max_length=255 , blank=True, null=True)
  rating           = models.FloatField(max_length=255 , blank=True, null=True, default='5.0')

  profile_img      = models.ImageField(blank=True, default="default.jpg")


  USERNAME_FIELD = 'email'
  #Username and email are required by defaults

  objects = UserManager()

  def __str__(self):
    return self.email

  def get_full_name(self):
    return self.first_name + " " + self.last_name

  def get_full_address(self):
    return self.street + " " + self.street_number + " " + self.zipcode + " " + self.city + " " + self.country

  def get_short_name(self):
    return self.first_name

  def has_perm(self, perm, obj=None):
    return True

  def has_module_perms(self, app_label):
    return True

  def is_client(self):
    if self.category_id > 0:
      return False
    else:
      return True

  @property
  def is_staff(self):
    return self.staff

  @property
  def is_superuser(self):
    return self.admin

  @property
  def is_active(self):
    return self.active

class Expertise(models.Model):
  title       = models.TextField()
  category_id = models.IntegerField(blank=True, null=True)

  def __str__(self):
    return self.title

class Message(models.Model):

  from_user        = models.ForeignKey(User, null=True, related_name='from_user')
  to_user          = models.ForeignKey(User, null=True, related_name='to_user')

  body             = models.TextField(max_length=5000, blank=True, null=True)
  status           = models.IntegerField(blank=True, null=True, default='1')
  replied_message  = models.IntegerField(blank=True, null=True)
  created_date     = models.DateTimeField(default=datetime.now)
  replied_date     = models.DateTimeField(auto_now=False, blank=True, null=True)

  def __str__(self):
    return self.body

class Rating(models.Model):

  from_user        = models.ForeignKey(User, null=True, related_name='rating_from_user')
  to_user          = models.ForeignKey(User, null=True, related_name='rating_to_user')

  body             = models.TextField(max_length=5000, blank=True, null=True)
  status           = models.IntegerField(blank=True, null=True, default='1')
  rating           = models.IntegerField(blank=True, null=True, default='5')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.body

class News(models.Model):

  title            = models.CharField(max_length=255, blank=True, null=True)
  source           = models.CharField(max_length=255, blank=True, null=True)
  link             = models.CharField(max_length=255, blank=True, null=True)
  body             = models.TextField(max_length=5000, blank=True, null=True)
  category_id      = models.IntegerField(blank=True, null=True, default='1')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.title

class Interviews(models.Model):

  title            = models.CharField(max_length=255, blank=True, null=True)
  body             = models.TextField(max_length=5000, blank=True, null=True)
  user_id          = models.ForeignKey(User, null=True, related_name='written_by')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.title

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from webapp.models import User
from webapp.models import Message
from webapp.models import Rating

class MessageForm(forms.ModelForm):

  class Meta:
    model    = Message
    fields   = (
      'to_user',
      'from_user',
      'replied_message',
      'body'
      )

    def save(self, commit=True):
      message                  = super(MessageForm, self)
      message.user_from        = self.cleaned_data('from_user')
      message.user_to          = self.cleaned_data('to_user')
      message.replied_message  = self.cleaned_data('replied_message')
      message.body             = self.cleaned_data('body')

      if commit:
        message.save()

      return message

class RatingForm(forms.ModelForm):

  class Meta:
    model    = Rating
    fields   = (
      'to_user',
      'from_user',
      'rating',
      'body'
      )

    def save(self, commit=True):
      rating                  = super(RatingForm, self)
      rating.user_from        = self.cleaned_data('from_user')
      rating.user_to          = self.cleaned_data('to_user')
      rating.rating           = self.cleaned_data('rating')
      rating.body             = self.cleaned_data('body')

      if commit:
        rating.save()

      return rating

class RegistrationForm(UserCreationForm):

  email = forms.EmailField(required=True)

  class Meta:
    model    = User
    fields   = (
      'category_id',
      'first_name',
      'last_name',
      'bio',
      'company',
      'email',
      'password1',
      'password2',
      'phone',
      'mobile',
      'web',
      'district_id',
      'district',
      'country',
      'street',
      'street_number',
      'city',
      'zipcode',
      'latitude',
      'longtitude',
      'experience',
      'expertise',
      'hour_rate_from',
      'hour_rate_to',
      'profile_img'
      )
    def save(self, commit=True):

      user = super(RegistrationForm, self)

      user.category_id      = self.cleaned_data('category_id')
      user.email            = self.cleaned_data('email')
      user.password1        = self.cleaned_data('password1')
      user.password2        = self.cleaned_data('password2')
      user.first_name       = self.cleaned_data('first_name')
      user.last_name        = self.cleaned_data('last_name')
      user.phone            = self.cleaned_data('phone')
      user.mobile           = self.cleaned_data('mobile')
      user.web              = self.cleaned_data('web')
      user.street           = self.cleaned_data('street')
      user.street_number    = self.cleaned_data('street_number')
      user.city             = self.cleaned_data('city')
      user.country          = self.cleaned_data('country')
      user.zipcode          = self.cleaned_data('zipcode')
      user.district         = self.cleaned_data('district')
      user.latitude         = self.cleaned_data('latitude')
      user.longtitude       = self.cleaned_data('longtitude')
      user.experience       = self.cleaned_data('experience')
      user.hour_rate_from   = self.cleaned_data('hour_rate_from')
      user.hour_rate_to     = self.cleaned_data('hour_rate_to')
      user.bio              = self.cleaned_data('bio')
      user.profile_img      = self.cleaned_data('profile_img')

      if commit:
        user.save()

      return user

webapp/templates/webapp/partials/expert.html
{% load i18n %}

<li class="user-box category-{{ expert.category_id }}">

   <a href="/webapp/expert/?id={{ expert.id }}&category_id={{ expert.category_id }}&district_id={{expert.district_id}}&district={{ expert.district }}&expertise={{ expertise_ids }}&experience_minimal={{ experience_minimal }}&hour_rate_maximal={{ hour_rate_maximal }}&rating_minimal={{ rating_minimal }}">

    <div class="category-icon">
      {% if expert.category_id == 1 %}
        <i class="fas fa-balance-scale"></i>
      {% elif expert.category_id == 2 %}
        <i class="fas fa-calculator"></i>
      {% else %}
        <i class="fas fa-bullhorn"></i>
      {% endif %}
    </div>
    <div class="user-box-top">
      <div class="profile-pic" style="background: #f2f2f2 url('/webapp/media/thumbs/{{ expert.profile_img }}') center center no-repeat; background-size: cover;" >
      </div>
      <div class="user-full-name">
        {{ expert.first_name }}
        {{ expert.last_name }}
      </div>
      <div  class="distric">
        <i class="fas fa-map-marker-alt"></i>
        {{ expert.district}}
      </div>
    </div>
    <div class="user-box-bottom">
      <div class="user-value long">
        <label>{% trans 'Experience' %}</label>
        <div class="value">{{ expert.experience}}</div>
      </div>
      <div class="user-value long">
        {% if expert.hour_rate_from == 200 and expert.hour_rate_to == 5000 %}

        {% else %}
          {% if expert.category_id == 3 %}
            <label>{% trans 'NS' %}</label>
          {% else %}
            <label>{% trans 'Hour rate' %}</label>
          {% endif %}
          <div class="value">{{ expert.hour_rate_from}} - {{ expert.hour_rate_to}} </div>
        {% endif %}
      </div>
      <div class="user-value">
        <label>{% trans 'Rating' %}</label>
        <div class="value">
          {% if expert.rating %}
            {{ expert.rating|floatformat:1 }}
          {% endif %}
          <i class="fas fa-star"></i>
        </div>
      </div>
     </div>
   </a>
</li>

webapp/templates/webapp/partials/expert_search_filter.html
{% load i18n %}

<div class="row" id="filters">

  <div class="page">

    <div class="filter-switch active">
      <i class="fas fa-sliders-h"></i>
      <i class="fas fa-times-circle"></i>
      <span>{% trans 'Filters' %}</span>
    </div>


    <form action="" method="get" id="experience-search-filter">

        <input
          type="hidden"
          name="category_id"
          {% if request.GET.category_id != None %}
            value="{{ request.GET.category_id }}"
          {% else %}
            value="1"
          {% endif %}
          />

       <input
          type="hidden"
          name="district_id"
          {% if request.GET.district_id != None %}
            value="{{ request.GET.district_id }}"
          {% else %}
            value="1"
          {% endif %}
          />

       <input
          type="hidden"
          name="district"
          {% if request.GET.district != None %}
            value="{{ request.GET.district }}"
          {% else %}
            value="Praha 1"
          {% endif %}
          />


        <!-- SLIDER FOR EXPERTISE -->
        <div class="row">
        <div class="input-field">
          {% for expertise_value in expertieses %}
            <div class="tag" data-expertise-id="{{ expertise_value.id }}">
              {{ expertise_value.title }}
              <i class="fas fa-check"></i>
            </div>
          {% endfor %}
          <input
            type="hidden"
            id="id_expertise"
            name="expertise"
            {% if request.GET.expertise != None %}
              value="{{ request.GET.expertise }}"
            {% endif %}
          />
        </div>

        <!-- SLIDER FOR EXPERIENCE -->
        <div class="input-field col s12 m12 l4 erp">
          <label class="custom-label">
            {% trans 'Minimal Experience (in years):' %}
            <span class="label-helper">
              <span id="experience"></span>
            </span>
          </label>

          <div id="experience-slider-minimal"></div>

          <input
            type="number"
            id="id_experience_minimal"
            name="experience_minimal"
            {% if request.GET.experience_minimal != None %}
              value="{{ request.GET.experience_minimal }}"
            {% else %}
              value="0"
            {% endif %}
            />

        </div>


        <!-- SLIDER FOR RATE -->
        <div class="input-field col s12 m12 l4 erp">
          <label class="custom-label">
            {% if request.GET.category_id == "3" %}
              {% trans 'Maximal Normopage Rate:' %}
            {% else %}
              {% trans 'Maximal Hour Rate:' %}
            {% endif %}
            <span class="label-helper">
              <span id="rate"></span>
            </span>
          </label>

          <div id="rate-slider-maximal"></div>

          <input
            type="number"
            id="id_hour_rate_maximal"
            name="hour_rate_maximal"
            {% if request.GET.hour_rate_maximal != None %}
              value="{{ request.GET.hour_rate_maximal }}"
            {% else %}
              value="1000000"
            {% endif %}
            />
        </div>


        <!-- SLIDER FOR MIN RATING -->
        <div class="input-field col s12 m12 l4 erp">

          <label class="custom-label">
            {% trans 'Minimal Rating:' %}
            <span class="label-helper">
              <span id="rating"></span>
            </span>
          </label>

          <div id="rating-slider"></div>

          <input
            type="number"
            step="any"
            id="id_rating_minimal"
            name="rating_minimal"
            {% if request.GET.rating_minimal != None %}
              value="{{ request.GET.rating_minimal }}"
            {% else %}
              value="0"
            {% endif %}
            />
        </div>
        </div>
      <input type="submit" class="btn" value="{% trans 'Apply Filter' %}" />
    </form>
  </div>
</div>

webapp/templates/webapp/partials/footer-form.html
{% load i18n %}

<div class="footer-message-top clearfix">
  <div class="close-fm">
    <i class="fas fa-times-circle"></i>
  </div>

  <h4>{% trans 'Hello' %}</h4>
  <p>{% trans 'Need help? Ask us anything.' %}</p>
</div>

<form action="/webapp/contact/" method="post">
  {% csrf_token %}
  <div class="form-cover">
    <div class="input-field first">
      <input type="email" id="id_email_ff" name="email" data-required="true" />
      <label id="id_email__ff">{% trans 'Email' %}</label>
    </div>
    <div class="input-field">
      <textarea type="text" id="id_message" name="message" data-required="true"></textarea>
      <label id="id_message">{% trans 'Question' %}</label>
    </div>
  </div>
  <input class="form-submit" type="submit" value="{% trans 'Send' %}" />
</form>

webapp/templates/webapp/partials/footer.html
{% load i18n %}

<div class="languages">
  <div class="page">
    <a href="/lang/?lang=cs">Cesky</a>
    <a href="/lang/?c=en">English</a>
  </div>
</div>

<footer class="clearfix page">
  <div class="row">
    <ul class="col s4">
      <li><a href="/about/">{% trans 'About us' %}</a></li>
      <li><a href="mailto:support@localexperts.cz">{% trans 'Contact us' %}</a></li>
      <li><a href="/interviews/">{% trans 'Interviews' %}</a></li>
    </ul>
    <ul class="col s4">
      <li><a href="/terms/">{% trans 'Terms' %}</a></li>
      <li><a href="/privacy/">{% trans 'Privacy' %}</a></li>
      <li><a href="/press">{% trans 'Press & Media' %}</a></li>
    </ul>
    <ul class="col s4">
      <li><a href="https://www.facebook.com/toplocalexperts/">{% trans 'Facebook' %}</a></li>
      <li><a href="https://www.instagram.com/local.experts/">{% trans 'Instagram' %}</a></li>
      <li><a href="https://twitter.com/localexpertscz">{% trans 'Twitter' %}</a></li>
    </ul>
  </div>

  <div class="footer-form-btn">
    <i class="fas fa-comments"></i>
  </div>

  <div class="footer-form">
    {% include 'webapp/partials/footer-form.html' %}
  </div>
</footer>

webapp/templates/webapp/partials/logo.html
{% load i18n %}

  <div class="top-left">
    <a href="/" id="logo">Expert New</a>
  </div>

webapp/templates/webapp/partials/nav.html
{% load i18n %}

<div id="top" class="clearfix">

  {% include 'webapp/partials/logo.html' %}

  {% if user.is_authenticated %}
    <div class="top-right">
      <a class="profile-button logout" href="/logout">
        <i class="fas fa-power-off"></i>
        <span>{% trans 'Logout' %}</span>
      </a>
      {% if unread_messages_count > 0 %}
        <a href="/webapp/messages/" class="notification">
          <i class="fas fa-bell"></i>
          <span class="number">{{ unread_messages_count }}</span>
        </a>
      {% else %}
        <a href="/webapp/messages/" class="profile-button">
          <i class="fas fa-inbox"></i>
          <span>{% trans 'Messages' %}</span>
        </a>
      {% endif %}

      {% if user.is_client %}

      {% else %}
        <a class="profile-button" href="/webapp/expert/?id={{ request.user.id }}">
          <i class="fas fa-user"></i>
          <span>{% trans 'Your Profile' %}</span>
        </a>
      {% endif %}

    </div>
  {% else %}
    <div class="top-right logout-links">
      <a class="profile-button" href="/login">
        <i class="fas fa-power-off"></i>
        <span>{% trans 'Login' %}</span>
      </a>
      <a class="profile-button" href="/register">
        <i class="fas fa-user-plus"></i>
        <span>{% trans 'Register' %}</span>
      </a>

      <a class="profile-button" href="/interviews">
        <i class="fas fa-comment"></i>
        <span>{% trans 'Interviews' %}</span>
      </a>
    </div>
  {% endif %}

</div>

webapp/templates/webapp/partials/sidebar_message.html
{% load i18n %}

<div class="message-sidebar sidebar category-{{ expert.category_id }}">
  <div class="input-spacing">
    <div class="close-sideber">
      <i class="fas fa-times-circle"></i>
    </div>
  </div>

  {% if user.is_authenticated %}
    <form action="/webapp/create_message/" method="post">
      {% csrf_token %}
      <input type="hidden" name="to_user" id="to_user_id" value="{{ expert.id }}" />
      <input type="hidden" name="from_user" id="from_user_id" value="{{ request.user.id }}" />
      <input type='hidden' name="replied_message" id="replied_message_id" value="0" />
      <div class="input-spacing">
        <div class="input-field">
          <textarea type="text" id="id_body" name="body" required="true" data-required="true" autofocus></textarea>
          <label for="id_body">{% trans 'Send Message to Expert' %}</label>
        </div>
      </div>
      <div class="input-spacing">
        <input class="btn" type="submit" name="submit" value="{% trans 'Send' %}" />
      </div>
    </form>
  {% else %}
    {% include 'marketing/not_logged_in.html' %}
  {% endif %}
</div>

webapp/templates/webapp/partials/sidebar_rating.html
{% load i18n %}

<div class="rating-sidebar sidebar category-{{ expert.category_id }}" >
  <div class="input-spacing">
    <div class="close-sideber">
      <i class="fas fa-times-circle"></i>
    </div>
  </div>

  {% if user.is_authenticated %}
    <form action="/webapp/create_rating/" method="post">
      {% csrf_token %}
      <input type="hidden" name="to_user" id="to_user_id" value="{{ expert.id }}" />
      <input type="hidden" name="from_user" id="from_user_id" value="{{ request.user.id }}" />
      <div class="input-spacing etp">
        <div class="input-field">
          <textarea type="text" id="id_body" name="body" required="true" data-required="true" autofocus></textarea>
          <label for="id_body">{% trans 'Your rating text' %}</label>
        </div>
      </div>
      <div class="input-spacing">
        <label for="id_rating" class="active">{% trans 'Your rating' %}</label>
        <div class="input-field">
          <div class="star-rating">
            <i class="far fa-star" data-value="1"></i>
            <i class="far fa-star" data-value="2"></i>
            <i class="far fa-star" data-value="3"></i>
            <i class="far fa-star" data-value="4"></i>
            <i class="far fa-star" data-value="5"></i>
          </div>
          <input type='hidden' name="rating" id="id_rating" value="5" />
        </div>
      </div>
      <div class="input-spacing">
        <input class="btn" type="submit" name="submit" value="{% trans 'Send' %}" />
      </div>
    </form>
  {% else %}
    {% include 'marketing/not_logged_in.html' %}
  {% endif %}
</div>

webapp/templates/webapp/partials/sidebar_sharing.html
{% load i18n %}

<div class="sharing-sidebar sidebar category-{{ expert.category_id }}" >
  <div class="input-spacing">
    <div class="close-sideber">
      <i class="fas fa-times-circle"></i>
    </div>
  </div>

  <div class="input-spacing clearfix">
    <h4>{% trans 'Share with friends today' %}</h4>
    <div class="sharethis-inline-share-buttons"></div>
  </div>
</div>

webapp/templates/webapp/partials/step_buttons.html
{% load i18n %}

<button class="btn box-stepper">{% trans 'Next  →'%}</button>
<button class="btn box-stepper-back">{% trans '←  Back '%}</button>
<input class="btn form-submit erm process-save-btn" type="submit" value="{% trans 'I am done editing. Save and close' %}" />