le/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^', include('webapp.urls')),
    url(r'^login/',  RedirectView.as_view(url='/webapp/login')),
    url(r'^logout/',  RedirectView.as_view(url='/webapp/logout')),
    url(r'^register/',  RedirectView.as_view(url='/webapp/register')),
    url(r'^register_expert/',  RedirectView.as_view(url='/webapp/register_expert')),
    url(r'^register_client/',  RedirectView.as_view(url='/webapp/register_client')),
    url(r'^experts_details/',  RedirectView.as_view(url='/webapp/experts_details')),
    url(r'^clients_details/',  RedirectView.as_view(url='/webapp/clients_details')),

    url(r'^webapp/', include('webapp.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls'))
]

webapp/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
from webapp.views import terms, privacy, about, logout_user, search, messages, news, interviews, create_message, create_rating, register, register_expert, register_client

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^experts_details/$', views.experts_details, name = 'experts_details'),
    url(r'^clients_details/$', views.clients_details, name = 'clients_details'),
    url(r'^login/', login, {'template_name': 'registration/login.html' }),
    url(r'^logout/', logout_user),
    url(r'^register_expert/$', views.register_expert, name = 'register_expert'),
    url(r'^register_client/$', views.register_client, name = 'register_client'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^search/$', views.search, name = 'search'),
    url(r'^expert/$', views.expert, name = 'expert'),
    url(r'^messages/$', views.messages, name = 'messages'),
    url(r'^news/$', views.news, name = 'news'),
    url(r'^interviews/$', views.interviews, name = 'interviews'),
    url(r'^update_profile/$', views.update_profile, name = 'update_profile'),
    url(r'^create_message/$', views.create_message, name = 'create_message'),
    url(r'^create_rating/$', views.create_rating, name = 'create_rating'),
    url(r'^terms/$', views.terms, name = 'terms'),
    url(r'^privacy/$', views.privacy, name = 'privacy'),
    url(r'^about/$', views.about, name = 'about'),
    url(r'^press/$', views.press, name = 'press'),
    url(r'^contact/$', views.contact, name = 'contact'),
    url(r'^remove_profile/$', views.remove_profile, name = 'remove_profile'),
    url(r'^lang/$', views.lang, name = 'lang'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import (
  AbstractBaseUser, BaseUserManager
)

from django_countries.fields import CountryField
from datetime import datetime

class UserManager(BaseUserManager):

  def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
    if not email:
      raise ValueError("Users must have email address")
    if not password:
      raise ValueError("Users must have password")

    user = self.model(
      email = self.normalize_email(email)
    )

    user.set_password(password)

    user.staff   = is_staff
    user.admin   = is_admin
    user.active  = is_active

    user.save(using=self._db)
    return user

  def create_superuser(self, email, password=None):
    user = self.create_user(
      email,
      password=password,
      is_admin=True
    )
    return user

  def create_staff(self, email, password=None):
    user = self.create_user(
      email,
      password=password,
      is_staff=True
    )
    return user



#Custom User
class User(AbstractBaseUser):
  email            = models.EmailField(max_length=255, unique=True)
  active           = models.BooleanField(default=True)
  staff            = models.BooleanField(default=False)
  admin            = models.BooleanField(default=False)
  timestamp        = models.DateTimeField(auto_now_add=True)

  first_name       = models.CharField(max_length=255, blank=True, null=True)
  last_name        = models.CharField(max_length=255 , blank=True, null=True)
  username         = models.CharField(max_length=255 , blank=True, null=True)

  phone            = models.CharField(max_length=255, blank=True, null=True)
  mobile           = models.CharField(max_length=255, blank=True, null=True)
  web              = models.CharField(max_length=255, blank=True, null=True)

  street           = models.CharField(max_length=255, blank=True, null=True)
  street_number    = models.CharField(max_length=255, blank=True, null=True)
  city             = models.CharField(max_length=255, blank=True, null=True)
  country          = CountryField(default ='CZ')
  zipcode          = models.CharField(max_length=255, blank=True, null=True)
  district         = models.CharField(max_length=255, blank=True, null=True)
  district_id      = models.IntegerField(blank=True, null=True)

  latitude         = models.CharField(max_length=255, blank=True, null=True)
  longtitude       = models.CharField(max_length=255, blank=True, null=True)

  company          = models.CharField(max_length=255, blank=True, null=True)
  category_id      = models.IntegerField(blank=True, null=True)
  experience       = models.IntegerField(blank=True, null=True)

  hour_rate_from   = models.IntegerField(blank=True, null=True)
  hour_rate_to     = models.IntegerField(blank=True, null=True)

  bio              = models.TextField(max_length=5000, blank=True, null=True)
  expertise        = models.CharField(max_length=255 , blank=True, null=True)
  rating           = models.FloatField(max_length=255 , blank=True, null=True, default='5.0')

  profile_img      = models.ImageField(blank=True, default="default.jpg")


  USERNAME_FIELD = 'email'
  #Username and email are required by defaults

  objects = UserManager()

  def __str__(self):
    return self.email

  def get_full_name(self):
    return self.first_name + " " + self.last_name

  def get_full_address(self):
    return self.street + " " + self.street_number + " " + self.zipcode + " " + self.city + " " + self.country

  def get_short_name(self):
    return self.first_name

  def has_perm(self, perm, obj=None):
    return True

  def has_module_perms(self, app_label):
    return True

  def is_client(self):
    if self.category_id > 0:
      return False
    else:
      return True

  @property
  def is_staff(self):
    return self.staff

  @property
  def is_superuser(self):
    return self.admin

  @property
  def is_active(self):
    return self.active

class Expertise(models.Model):
  title       = models.TextField()
  category_id = models.IntegerField(blank=True, null=True)

  def __str__(self):
    return self.title

class Message(models.Model):

  from_user        = models.ForeignKey(User, null=True, related_name='from_user')
  to_user          = models.ForeignKey(User, null=True, related_name='to_user')

  body             = models.TextField(max_length=5000, blank=True, null=True)
  status           = models.IntegerField(blank=True, null=True, default='1')
  replied_message  = models.IntegerField(blank=True, null=True)
  created_date     = models.DateTimeField(default=datetime.now)
  replied_date     = models.DateTimeField(auto_now=False, blank=True, null=True)

  def __str__(self):
    return self.body

class Rating(models.Model):

  from_user        = models.ForeignKey(User, null=True, related_name='rating_from_user')
  to_user          = models.ForeignKey(User, null=True, related_name='rating_to_user')

  body             = models.TextField(max_length=5000, blank=True, null=True)
  status           = models.IntegerField(blank=True, null=True, default='1')
  rating           = models.IntegerField(blank=True, null=True, default='5')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.body

class News(models.Model):

  title            = models.CharField(max_length=255, blank=True, null=True)
  source           = models.CharField(max_length=255, blank=True, null=True)
  link             = models.CharField(max_length=255, blank=True, null=True)
  body             = models.TextField(max_length=5000, blank=True, null=True)
  category_id      = models.IntegerField(blank=True, null=True, default='1')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.title

class Interviews(models.Model):

  title            = models.CharField(max_length=255, blank=True, null=True)
  body             = models.TextField(max_length=5000, blank=True, null=True)
  user_id          = models.ForeignKey(User, null=True, related_name='written_by')
  created_date     = models.DateTimeField(default=datetime.now)

  def __str__(self):
    return self.title

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from webapp.models import User
from webapp.models import Message
from webapp.models import Rating

class MessageForm(forms.ModelForm):

  class Meta:
    model    = Message
    fields   = (
      'to_user',
      'from_user',
      'replied_message',
      'body'
      )

    def save(self, commit=True):
      message                  = super(MessageForm, self)
      message.user_from        = self.cleaned_data('from_user')
      message.user_to          = self.cleaned_data('to_user')
      message.replied_message  = self.cleaned_data('replied_message')
      message.body             = self.cleaned_data('body')

      if commit:
        message.save()

      return message

class RatingForm(forms.ModelForm):

  class Meta:
    model    = Rating
    fields   = (
      'to_user',
      'from_user',
      'rating',
      'body'
      )

    def save(self, commit=True):
      rating                  = super(RatingForm, self)
      rating.user_from        = self.cleaned_data('from_user')
      rating.user_to          = self.cleaned_data('to_user')
      rating.rating           = self.cleaned_data('rating')
      rating.body             = self.cleaned_data('body')

      if commit:
        rating.save()

      return rating

class RegistrationForm(UserCreationForm):

  email = forms.EmailField(required=True)

  class Meta:
    model    = User
    fields   = (
      'category_id',
      'first_name',
      'last_name',
      'bio',
      'company',
      'email',
      'password1',
      'password2',
      'phone',
      'mobile',
      'web',
      'district_id',
      'district',
      'country',
      'street',
      'street_number',
      'city',
      'zipcode',
      'latitude',
      'longtitude',
      'experience',
      'expertise',
      'hour_rate_from',
      'hour_rate_to',
      'profile_img'
      )
    def save(self, commit=True):

      user = super(RegistrationForm, self)

      user.category_id      = self.cleaned_data('category_id')
      user.email            = self.cleaned_data('email')
      user.password1        = self.cleaned_data('password1')
      user.password2        = self.cleaned_data('password2')
      user.first_name       = self.cleaned_data('first_name')
      user.last_name        = self.cleaned_data('last_name')
      user.phone            = self.cleaned_data('phone')
      user.mobile           = self.cleaned_data('mobile')
      user.web              = self.cleaned_data('web')
      user.street           = self.cleaned_data('street')
      user.street_number    = self.cleaned_data('street_number')
      user.city             = self.cleaned_data('city')
      user.country          = self.cleaned_data('country')
      user.zipcode          = self.cleaned_data('zipcode')
      user.district         = self.cleaned_data('district')
      user.latitude         = self.cleaned_data('latitude')
      user.longtitude       = self.cleaned_data('longtitude')
      user.experience       = self.cleaned_data('experience')
      user.hour_rate_from   = self.cleaned_data('hour_rate_from')
      user.hour_rate_to     = self.cleaned_data('hour_rate_to')
      user.bio              = self.cleaned_data('bio')
      user.profile_img      = self.cleaned_data('profile_img')

      if commit:
        user.save()

      return user

webapp/templates/webapp/expert.html
{% extends "webapp/base.html" %}
{% block content %}
{% load i18n %}

{% if message_sent == 'true' %}
  {% include 'expert/message_sent.html' %}
{% endif %}

{% if rating_sent == 'true' %}
  {% include 'expert/rating_applied.html' %}
{% endif %}

{% load staticfiles %}

<div class="expert category-{{ expert.category_id }}">

  <div class="bg-top" style="background: url('/webapp/media/{{ expert.profile_img }}') center center no-repeat; background-size: cover;" >
    <div class="top-cover">

      {% include 'webapp/partials/nav.html' %}

      <div  class="top-expert-content">
        <div class="expert-category-icon clearfix">
          {% if expert.category_id == 1 %}
            <i class="fas fa-balance-scale"></i>
            <span>{% trans 'Lawyer'  %}</span>
          {% elif expert.category_id == 2 %}
            <i class="fas fa-calculator"></i>
            <span>{% trans 'Accountant'  %}</span>
          {% else %}
            <i class="fas fa-bullhorn"></i>
            <span>{% trans 'Translator'  %}</span>
          {% endif %}
        </div>

        <div class="expert-title clearfix">
          <h1>{{ expert.first_name }} {{ expert.last_name }}</h1>
          <div class="clearfix">
            <div class="expert-title-section">
              {% if expert.company != None %}
                <i class="fas fa-building"></i>
                <span>{{ expert.company }}</span>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="expert-values clearfix">
          <div class="expert-value-section">
            <div class="expert-value-header">{% trans 'Rating' %}</div>
            <div class="expert-value-iteger">
              {% if expert.rating %}
                <span>{{ expert.rating|floatformat:1 }}</span>
              {% endif %}
              <i class="fas fa-star"></i>
            </div>
          </div>

          {% if expert.hour_rate_from == 200 and expert.hour_rate_to == 5000 %}
          {% else %}
            <div class="expert-value-section">
              <div class="expert-value-header">
              {% if expert.category_id == 3 %}
                {% trans 'Normo-page' %}
              {% else %}
                {% trans 'Hour Rate' %}
              {% endif %}
              </div>
              <div class="expert-value-iteger">{{ expert.hour_rate_from }}-{{ expert.hour_rate_to }}</div>
            </div>
          {% endif %}

          <div class="expert-value-section">
            <div class="expert-value-header">{% trans 'Years' %}</div>
            <div class="expert-value-iteger">{{ expert.experience }}</div>
          </div>


          {% if expert.id == request.user.id %}
            <!-- Your Profile -->
            <div class="expert-value-section last">
              <a href="/webapp/update_profile/?id={{ expert.id }}" class="message-button">
                <i class="fas fa-edit"></i>
                <span>{% trans 'Update Your Profile' %}</span>
              </a>
              <a hre="#!" class="message-button  modal-trigger" data-target="modal1">
                <i class="fas fa-user-times"></i>
                <span>{% trans 'Remove Profile' %}</span>
            </a>
            </div>

            <div id="modal1" class="modal">
              <div class="modal-content">
                <h4>{% trans 'You are about to remove your profile forever' %}</h4>
                <p>{% trans 'Are you sure?' %}</p>
              </div>
              <a href="#!" class="modal-close marketing-button secondary half-width">{% trans 'No, not now.' %}
              <a href="/remove_profile/" class="marketing-button half-width">{% trans 'Yes' %}</a>
            </div>

          {% else %}
            <div class="expert-value-section last">
                <a href="" class="message-button" id="send-message">
                  <i class="far fa-envelope"></i>
                  <span>{% trans 'Message' %}</span>
                </a>
              <a href="" class="message-button" id="send-rating">
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <i class="far fa-star"></i>
                <span>{% trans 'Rate' %}</span>
              </a>
              <a href="" class="message-button" id="share">
                <i class="fas fa-share-alt"></i>
              </a>

            </div>
          {% endif %}

        </div>

        <div class="clearfix" id="expert-contacts">
          <div class="expert-title-section">
            {% if expert.email != None %}
              <i class="fas fa-envelope"></i>
              <span><a href="mailto:{{ expert.email }}">{{ expert.email }}</a></span>
            {% endif %}
          </div>
          <div class="expert-title-section">
            {% if expert.web  != None %}
              <i class="fas fa-home"></i>
              <span><a target="_blank" href="{{expert.web}}">{{ expert.web }}</a></span>
            {% endif %}
          </div>
          <div class="expert-title-section">
            {% if expert.phone  != None %}
              <i class="fas fa-phone"></i>
              <span>{{ expert.phone }}</span>
            {% endif %}
          </div>
          <div class="expert-title-section">
            {% if expert.mobile  != None %}
              <i class="fas fa-mobile-alt"></i>
              <span>{{ expert.mobile }}</span>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="page">
    <div class="row">
      <div class="expert-sidebar sidebar-nav col s12 l4">
        <ul>
          <li class="active" data-target="#welcome">{% trans '01 Welcome' %}</li>
          <li data-target="#expertise">{% trans '02 Expertise' %}</li>
          <li data-target="#location">{% trans '03 Location' %}</li>
          <li data-target="#reviews">{% trans '04 Reviews' %}</li>
          <li data-target="#interviews">{% trans '05 Interview' %}</li>
        </ul>
      </div>

      <div class="expert-main  main-content col s12 l8">
        <div class="expert-section" id="welcome">
          <h2>{% trans 'Welcome' %}</h2>
          <div class="expert-section-text">
            {% if  expert.id == request.user.id and expert.bio == "" %}
              <p class="no-data do-something"><i class="fas fa-pencil-alt"></i>{% trans 'You have not defined any welcome text.' %} <a href="/webapp/update_profile/?id={{ expert.id }}">{% trans 'You can add it in here.' %}</a></p>
            {% else %}
              {{ expert.bio|linebreaks }}
            {% endif %}
          </div>
        </div>

        <div class="expert-section" id="expertise">
          <h2>{% trans 'Expertise' %}</h2>
          <div class="expert-section-text">
            {% if  expert.id == request.user.id and expertieses == "" %}
              <p class="no-data do-something"><i class="fas fa-pencil-alt"></i>{% trans 'You have not defined any expertises.' %} <a href="/webapp/update_profile/?id={{ expert.id }}">{% trans 'You can add them in here.' %}</a></p>
            {% else %}
              {% if expertieses == "" %}
                <p class="no-data"><i class="fas fa-tags"></i>{% trans 'Unknown expertieses.' %}</p>
              {% else %}
                {% for expertise_value in expertieses %}
                  <div class="expert-tag">
                    {{ expertise_value.title }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endif %}
          </div>
        </div>

        <div class="expert-section" id="location">
          <h2>{% trans 'Location' %}</h2>
          <div class="expert-section-text clearfix">
            {% if  expert.id == request.user.id and expert.street == None %}
              <p class="no-data do-something"><i class="fas fa-pencil-alt"></i>{% trans 'You have not defined your full location.' %}<a href="/webapp/update_profile/?id={{ expert.id }}">{% trans 'You can add it in here.' %}</a></p>
            {% else %}
              {% if  expert.street == None %}
                <p class="no-data"><i class="fas fa-map"></i>{% trans 'Unknown location.' %}</p>
              {% else %}
                <div class="address">
                  <i class="fas fa-map-marker-alt"></i>
                  <span>{{ expert.street }} {{ expert.street_number }}, {{ expert.zipcode }} {{ expert.city }}, {{ expert.country }}</span>
                </div>
                {% if  expert.latitude > 0 %}
                  <a target="_blank" href='https://www.google.com/maps?saddr=My+Location&&daddr={{ expert.latitude }},{{ expert.longtitude }}' class="map-button">
                    <i class="fas fa-external-link-alt"></i>
                    <span>{% trans 'Directions' %}</span>
                  </a>
                {% endif %}
              {% endif %}
            {% endif %}
          </div>

         <!-- GOOGLE MAP FOR LOCATION -->
          <div id="google-map" class="clearfix">
            <input
              id="id_longtitude"
              name="longtitude"
              type="hidden"
              value="{{ expert.longtitude }}"
              />
            <input
              id="id_latitude"
              name="latitude"
              type="hidden"
              value="{{ expert.latitude }}"
              />
            {% if  expert.latitude > 0 %}
              <div id="map-canvas" style="height:500px; width:100%"></div>
            {% endif %}
          </div>
        </div>
        <div class="expert-section" id="reviews">
          <h2>{% trans 'Reviews' %}</h2>

          {% if ratings.count < 1 %}
            <p class="no-data"><i class="fas fa-users"></i>{% trans 'There are no reviews yet.' %}</p>
          {% endif %}


          {% for rating in ratings %}
            <div class="expert-section-text clearfix">
              <div class="user-rating">
                <div class="user-rating-base">
                  <strong>
                    {{ rating.to_user.first_name }}
                  </strong>
                  <span> - {{ rating.created_date|date:"d M Y" }}</span>
                </div>
                <div class="user-rating-body">
                  {{ rating.body |linebreaks}}
                </div>
              </div>
              <div class="user-rating-value">
                <div class="expert-value-section">
                  <div class="expert-value-header">{% trans 'Rating' %}</div>
                  <div class="expert-value-iteger">
                    <span>{{ rating.rating|floatformat:1 }}</span>
                    <i class="fas fa-star"></i>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>

        <div class="expert-section">
          {% if interview %}
            <h2>{% trans 'Interview' %}</h2>
            <div id="interviews">
              {{ interview.body|safe|linebreaks }}
            {% endif %}
          </div>
        </div>


      </div>
    </div>
  </div>


  {% if expert.id != request.user.id %}
    {% if experts.count > 0 %}
      <div id="other-experts">
        <h2>{% trans 'Other experts from your search' %}</h2>
        <ul class="user-boxes">
          {% for expert in experts %}
            {% include 'webapp/partials/expert.html' %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endif %}
</div>

{% include 'webapp/partials/sidebar_message.html' %}
{% include 'webapp/partials/sidebar_rating.html' %}
{% include 'webapp/partials/sidebar_sharing.html' %}


{% endblock %}

webapp/templates/webapp/messages.html
{% extends "webapp/base.html" %}
{% block content %}
{% load i18n %}


<div class="messages">

  <div class="bg-top">
    <div class="top-cover">
      {% include 'webapp/partials/nav.html' %}
      <div class="top-category-icon">
        <i class="fas fa-inbox"></i>
      </div>
      <h1>
        <span>{% trans 'Messages' %}</span>
      </h1>
    </div>
  </div>

  {% if user.is_client %}
    <a class="marketing-button full-width" href="/">
      <i class="fas fa-search"></i>
      <span>{% trans 'Search for an Expert' %}</span>
    </a>
  {% endif %}

  <div class="page">
    <div class="row">
      <div class="messages-sidebar sidebar-nav col s12 l4">
        <ul>
          <li class="active" data-target="#received_messages">{% trans '01 Received' %}</li>
          <li data-target="#sent_messages">{% trans '02 Sent' %}</li>
        </ul>
      </div>
      <div class="message-main main-content col s12 l8">

        <!-- Sent Messages -->
        <div class="message-table" id="sent_messages">

          {% if sent_message.count < 1%}
            <p class="no-data"><i class="fas fa-envelope"></i>{% trans 'You have not sent any messages so far.' %}</p>
          {% else %}

            <div class="header clearfix">
              <div class="status"></div>
              <div class="from">{% trans 'To' %}</div>
              <div class="replied"></div>
              <div class="recieved">{% trans 'Sent' %}</div>
            </div>

            {% for s_message in sent_message %}
            <div class="message-row clearfix">
              <div class="message-data clearfix">
                <div class="message-header clearfix">
                  <div class="status status-3">
                    <i class="fab fa-telegram-plane"></i>
                  </div><!-- Status -->
                  <div class="from">{{ s_message.to_user }}</div>
                  <div class="replied">{{ s_message.replied_date|date:"d M Y h:i:s "}}</div>
                  <div class="recieved">{{ s_message.created_date|date:"d M Y h:i:s " }}</div>
                </div><!-- Message Header -->
                <div class="message-body clearfix">
                  {{ s_message.body|linebreaks}}

                  {% if s_message.to_user.is_client %}
                  {% else %}
                    {% include 'webapp/partials/expert.html' with expert=s_message.to_user %}
                  {% endif %}

                </div><!-- Message Body -->
              </div><!-- Message Data -->
            </div><!-- Row -->
            {% endfor %}
          {% endif %}
        </div><!-- Message Table -->


        <!-- Received Messages -->
        <div class="message-table" id="received_messages">

          {% if received_message.count < 1%}
            <p class="no-data"><i class="fas fa-envelope"></i>{% trans 'You have not received any messages so far.' %}</p>
          {% else %}

            <div class="header clearfix">
              <div class="status"></div>
              <div class="from">{% trans 'From' %}</div>
              <div class="replied">{% trans 'Replied' %}</div>
              <div class="recieved">{% trans 'Received' %}</div>
            </div>

            {% for r_message in received_message %}
            <div class="message-row clearfix">
              <div class="message-data clearfix">
                <div class="message-header clearfix">
                  <div class="status status-{{ r_message.status }}">
                    {% if r_message.status == 1 %}
                      <i class="fas fa-bell"></i>
                    {% else %}
                      <i class="fas fa-check-circle"></i>
                    {% endif %}
                  </div><!-- Status -->
                  <div class="from">{{ r_message.from_user }}</div>
                  <div class="replied">{{ r_message.replied_date|date:"d M Y h:i:s "}}</div>
                  <div class="recieved">{{ r_message.created_date|date:"d M Y h:i:s " }}</div>
                </div><!-- Message Header -->
                <div class="message-body clearfix">
                  <div class="clearfix">
                    {{ r_message.body|linebreaks}}
                  </div>

                  {% if r_message.status == 1 %}
                    <a href="" class="reply-button">
                      <i class="fas fa-reply"></i>
                      <span>{% trans 'Reply' %}</span>
                    </a>

                    <form action="/webapp/create_message/" method="post" class="reply-form">
                      {% csrf_token %}
                      <input type="hidden" name="to_user" id="to_user_id" value="{{ r_message.from_user.id }}" />
                      <input type="hidden" name="from_user" id="from_user_id" value="{{ request.user.id }}" />
                      <input type='hidden' name="replied_message" id="replied_message_id" value="{{ r_message.id }}" />
                      <div class="input-field">
                        <textarea type="text" id="id_body" name="body" required="true"></textarea>
                        <label for="id_body">{% trans 'Specify Reply' %}</label>
                      </div>
                      <input class="btn" type="submit" name="submit" value="{% trans 'Send' %}" />
                    </form>
                  {% endif %}

                  {% if r_message.from_user.is_client %}
                  {% else %}
                    {% include 'webapp/partials/expert.html' with expert=r_message.from_user %}
                  {% endif %}

                </div><!-- Message Body -->
              </div><!-- Message Data -->
            </div><!-- Row -->
            {% endfor %}
          {% endif %}
        </div><!-- Message Table -->
      </div><!-- Message Main -->
    </div><!-- Row -->
  </div><!-- Page -->

  {% if user.is_client %}
    {% include 'includes/district_list.html' %}
  {% endif %}

</div><!-- Message -->

{% endblock %}

webapp/templates/webapp/search.html
{% extends "webapp/base.html" %}
{% block content %}
{% load i18n %}

<div class="search category-{{ category_id }}">

  <div class="bg-top">
    <div class="top-cover">

      {% include 'webapp/partials/nav.html' %}

      <div class="top-category-icon">
        {% if category_id == 1 %}
          <i class="fas fa-balance-scale"></i>
        {% elif category_id == 2 %}
          <i class="fas fa-calculator"></i>
        {% else %}
          <i class="fas fa-bullhorn"></i>
        {% endif %}
      </div>

      <h1>
        {% if category_id == 1 %}
          <span>{% trans 'Lawyers' %}</span>
        {% elif category_id == 2 %}
          <span>{% trans 'Accountants' %}</span>
        {% else %}
          <span>{% trans 'Translators' %}</span>
        {% endif %}
        {% trans 'in' %}
        <span>{{ district }}</span>
      </h1>
    </div>
  </div>

    {% include 'webapp/partials/expert_search_filter.html' %}

  <div class="page">
    <div class="row">
      <ul classes="user-boxes">
        {% if experts.count > 0 %}
          {% for expert in experts %}
            {% include 'webapp/partials/expert.html' %}
          {% endfor %}
        {% else %}
          <div class="no-data">
            <i class="fas fa-user-tag"></i>
            {% trans 'There are no data matching search criteria.' %}
          </div>
        {% endif %}
      </ul>

      <div class="no-data do-something ebm">
        <i class="fas fa-rocket"></i>
        {% trans 'We are just starting! We are adding experts on daily basis. Please come back again if you don not find what you are looking for.' %}
      </div>

    </div>
  </div>
</div>

{% endblock %}